In [6]:
import numpy as np
import matplotlib.pyplot as plt
import io

In [19]:
scanfile = '05_03_19-4.scan'

data1 = []
with open(scanfile, 'r') as f:
    start = False
    for line in f:
        if len(line)>1:
            line1 = line.split()[0]
            if line1 == '#Time':
                start = True
            if start:
                line2 = line.strip()
                if line2 == 'ALL:':
                    break
                data1 = np.append(data1, line)
data1 = np.genfromtxt(data1)
sum_data = data1[:, -1]
sum_data

array([1619.5 , 2799.5 , 2249.  , 1568.75, 1959.5 , 2431.5 , 2911.75,
       3239.5 , 3426.5 , 3547.5 , 3726.75, 3784.75, 3786.  , 3804.25,
       3761.  , 3741.75, 3748.5 , 3689.25, 3670.75, 3628.  , 3741.5 ])

In [72]:
def get_skip_line(scanfile):
    with open(scanfile, 'r') as f:
        skip = 0
        for line in f:
            if len(line)>1:
                line = line.strip()
                if line == 'ALL:':
                    print(f'\n{line} found at line no. {skip+1}\n')
                    return skip + 1
            skip += 1
    return f'ALL: is not found in the file'

def get_iterations(scanfile):
    iterations = np.array([])
    with open(scanfile, 'r') as f:
        for line in f:
            if line.startswith('#mass'):
                iterations = np.append(iterations, line.split(':')[-1]).astype(np.int64)
            else: continue
    return iterations

In [91]:
scanfile = '05_03_19-4.scan'

# Getting skip_line to reach the data points
# Getting iterations of each mass timescan
skip = get_skip_line(scanfile)
iterations = get_iterations(scanfile)

# opening File
file = np.genfromtxt(scanfile, skip_header = skip)
print(f'{file}; {file.shape}\n{file.T}; {file.T.shape}')

# Tranforming file shape
file_trans = file.T

# Mass
masses = np.array(list(set(file_trans[0])))
print(f'Time: {masses}\n{masses.shape}\n')

# Time
time = np.array(list(set(file_trans[1])))
print(f'Time: {time}\n{time.shape}\n')


ALL: found at line no. 34

[[ 18.7   0.    5. ]
 [ 18.7   5.    0. ]
 [ 18.7  10.    0. ]
 ...
 [ 52.7  90.    0. ]
 [ 52.7  95.    0. ]
 [ 52.7 100.    0. ]]; (588, 3)
[[ 18.7  18.7  18.7 ...  52.7  52.7  52.7]
 [  0.    5.   10.  ...  90.   95.  100. ]
 [  5.    0.    0.  ...   0.    0.    0. ]]; (3, 588)
Time: [40.7 18.7 52.7 24.7 25.7 27.7 28.7]
(7,)

Time: [  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]
(21,)



In [90]:
time.shape, masses.shape, iterations.shape, file.shape, 4*21*7

((21,), (7,), (7,), (588, 3), 588)

In [125]:
for iteration in iterations:
    print(iteration*len(time))
file.shape, file_trans.shape, file_trans, 4*21*27/iterations.sum(), len(file)/iterations.sum()

84
84
84
84
84
84
84


((588, 3), (3, 588), array([[ 18.7,  18.7,  18.7, ...,  52.7,  52.7,  52.7],
        [  0. ,   5. ,  10. , ...,  90. ,  95. , 100. ],
        [  5. ,   0. ,   0. , ...,   0. ,   0. ,   0. ]]), 81.0, 21.0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,