In [76]:
import numpy as np
import matplotlib.pyplot as plt
from uncertainties import unumpy as unp

In [93]:
def get_skip_line(scanfile):
    with open(scanfile, 'r') as f:
        skip = 0
        for line in f:
            if len(line)>1:
                line = line.strip()
                if line == 'ALL:':
                    print(f'\n{line} found at line no. {skip+1}\n')
                    return skip + 1
            skip += 1
    return f'ALL: is not found in the file'

def get_iterations(scanfile):
    iterations = np.array([])
    with open(scanfile, 'r') as f:
        for line in f:
            if line.startswith('#mass'):
                print(line)
                iterations = np.append(iterations, line.split(':')[-1]).astype(np.int64)
            else: continue
    return iterations
iterations = get_iterations(scanfile)

#mass18.70:	4

#mass24.70:	4

#mass25.70:	4

#mass27.70:	4

#mass28.70:	4

#mass40.70:	4

#mass52.70:	4



In [127]:
scanfile = '05_03_19-4.scan'

# Getting skip_line to reach the data points
# Getting iterations of each mass timescan
skip = get_skip_line(scanfile)
iterations = get_iterations(scanfile)

# opening File
data = np.genfromtxt(scanfile, skip_header = skip)
print(f'File shape: {data.shape}\n')

# Calculating the time step cycle and total no of masses (run)
cycle = int(len(data)/iterations.sum())
run = len(iterations)

# Time
time = data[:, 1][: cycle]
print(f'Time: {time}\t{time.shape}\n')

# Calculating mean and std_devs
j = 0
mean, error = [], []
mass = []
for num, iteration in enumerate(iterations):
    
    k = iteration*cycle
    
    print(f'### START {num} ###\n')
    print(f'Before: data[:, 2][{j}:{k+j}]\n')
    
    mass_value = data[:, 0][j: k+j][0]
    mass_sort = data[:, 2][j:k+j].reshape(iteration, cycle).mean(axis = 0)
    error_sort = data[:, 2][j:k+j].reshape(iteration, cycle).std(axis = 0)
    
    mass = np.append(mass, mass_value)
    mean = np.append(mean, mass_sort)
    error = np.append(error, error_sort)
    
    j = k + j
    
    print(f'After: j: {j}\n')
    print(f'Mass {num}: {mass_sort}\t{mass_sort.shape}\n')
    print(f'Error {num}: {error_sort}\t{error_sort.shape}\n')
    print(f'Before\nMean: {mean.shape}\t Error: {error.shape}\n')
    print(f'Total Mass: {mass}\n')
    print(f'### END {num} ###\n\n')

mean = mean.reshape(run, cycle)
error = error.reshape(run, cycle)

print(f'After\nMean: {mean.shape}\t Error: {error.shape}\n')

# calculating the SUM
mean_with_error = unp.uarray(mean, error)
sum_mean_with_error = mean_with_error.sum(axis = 0)
print(f'Mean with error: {mean_with_error.shape}\nSum with error: {sum_mean_with_error.shape}')


ALL: found at line no. 34

#mass18.70:	4

#mass24.70:	4

#mass25.70:	4

#mass27.70:	4

#mass28.70:	4

#mass40.70:	4

#mass52.70:	4

File shape: (588, 3)

Time: [  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]	(21,)

### START 0 ###

Before: data[:, 2][0:84]

After: j: 84

Mass 0: [1.25 0.   0.   0.   0.   0.   0.   0.25 0.   0.25 0.25 0.25 0.   1.
 2.   3.25 1.   0.5  1.25 0.75 1.  ]	(21,)

Error 0: [2.16506351 0.         0.         0.         0.         0.
 0.         0.4330127  0.         0.4330127  0.4330127  0.4330127
 0.         1.22474487 2.12132034 4.49305019 0.70710678 0.5
 1.08972474 0.8291562  0.70710678]	(21,)

Before
Mean: (21,)	 Error: (21,)

Total Mass: [18.7]

### END 0 ###


### START 1 ###

Before: data[:, 2][84:168]

After: j: 168

Mass 1: [1605.   2768.   2214.   1551.25 1937.   2398.   2863.25 3175.5  3357.75
 3462.5  3621.75 3666.5  3640.   3653.5  3593.25 3575.5  3557.   3489.
 3483.25 3449.75 3530.75]	(2

In [113]:
data.T[0].shape, data.T[0].reshape(run, 84).T[0], 

((588,), array([18.7, 24.7, 25.7, 27.7, 28.7, 40.7, 52.7]), 21.0)

In [ ]:
data.T[0].reshape(len(iterations), len(time)*iteration)

In [128]:
from uncertainties import unumpy as unp
temp = unp.uarray([1, 2, 3], [0.1, 0.2, 0.3])
unp.nominal_values(temp), unp.std_devs(temp)

(array([1., 2., 3.]), array([0.1, 0.2, 0.3]))

In [120]:
data[:, 1][: cycle]

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [105]:
4*21

84

In [33]:
iterations*len(time)

array([84, 84, 84, 84, 84, 84, 84], dtype=int64)